# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brandon/Documents/Entropy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brandon/Documents/Entropy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brandon/Documents/Entropy/CMakeFiles /home/brandon/Documents/Entropy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brandon/Documents/Entropy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SVM

# Build rule for target.
SVM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SVM
.PHONY : SVM

# fast build rule for target.
SVM/fast:
	$(MAKE) -f CMakeFiles/SVM.dir/build.make CMakeFiles/SVM.dir/build
.PHONY : SVM/fast

#=============================================================================
# Target rules for targets named Entropy

# Build rule for target.
Entropy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Entropy
.PHONY : Entropy

# fast build rule for target.
Entropy/fast:
	$(MAKE) -f CMakeFiles/Entropy.dir/build.make CMakeFiles/Entropy.dir/build
.PHONY : Entropy/fast

#=============================================================================
# Target rules for targets named Checker

# Build rule for target.
Checker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Checker
.PHONY : Checker

# fast build rule for target.
Checker/fast:
	$(MAKE) -f CMakeFiles/Checker.dir/build.make CMakeFiles/Checker.dir/build
.PHONY : Checker/fast

Checker.o: Checker.cpp.o

.PHONY : Checker.o

# target to build an object file
Checker.cpp.o:
	$(MAKE) -f CMakeFiles/Checker.dir/build.make CMakeFiles/Checker.dir/Checker.cpp.o
.PHONY : Checker.cpp.o

Checker.i: Checker.cpp.i

.PHONY : Checker.i

# target to preprocess a source file
Checker.cpp.i:
	$(MAKE) -f CMakeFiles/Checker.dir/build.make CMakeFiles/Checker.dir/Checker.cpp.i
.PHONY : Checker.cpp.i

Checker.s: Checker.cpp.s

.PHONY : Checker.s

# target to generate assembly for a file
Checker.cpp.s:
	$(MAKE) -f CMakeFiles/Checker.dir/build.make CMakeFiles/Checker.dir/Checker.cpp.s
.PHONY : Checker.cpp.s

Entropy.o: Entropy.cpp.o

.PHONY : Entropy.o

# target to build an object file
Entropy.cpp.o:
	$(MAKE) -f CMakeFiles/SVM.dir/build.make CMakeFiles/SVM.dir/Entropy.cpp.o
	$(MAKE) -f CMakeFiles/Entropy.dir/build.make CMakeFiles/Entropy.dir/Entropy.cpp.o
.PHONY : Entropy.cpp.o

Entropy.i: Entropy.cpp.i

.PHONY : Entropy.i

# target to preprocess a source file
Entropy.cpp.i:
	$(MAKE) -f CMakeFiles/SVM.dir/build.make CMakeFiles/SVM.dir/Entropy.cpp.i
	$(MAKE) -f CMakeFiles/Entropy.dir/build.make CMakeFiles/Entropy.dir/Entropy.cpp.i
.PHONY : Entropy.cpp.i

Entropy.s: Entropy.cpp.s

.PHONY : Entropy.s

# target to generate assembly for a file
Entropy.cpp.s:
	$(MAKE) -f CMakeFiles/SVM.dir/build.make CMakeFiles/SVM.dir/Entropy.cpp.s
	$(MAKE) -f CMakeFiles/Entropy.dir/build.make CMakeFiles/Entropy.dir/Entropy.cpp.s
.PHONY : Entropy.cpp.s

EntropyMain.o: EntropyMain.cpp.o

.PHONY : EntropyMain.o

# target to build an object file
EntropyMain.cpp.o:
	$(MAKE) -f CMakeFiles/Entropy.dir/build.make CMakeFiles/Entropy.dir/EntropyMain.cpp.o
.PHONY : EntropyMain.cpp.o

EntropyMain.i: EntropyMain.cpp.i

.PHONY : EntropyMain.i

# target to preprocess a source file
EntropyMain.cpp.i:
	$(MAKE) -f CMakeFiles/Entropy.dir/build.make CMakeFiles/Entropy.dir/EntropyMain.cpp.i
.PHONY : EntropyMain.cpp.i

EntropyMain.s: EntropyMain.cpp.s

.PHONY : EntropyMain.s

# target to generate assembly for a file
EntropyMain.cpp.s:
	$(MAKE) -f CMakeFiles/Entropy.dir/build.make CMakeFiles/Entropy.dir/EntropyMain.cpp.s
.PHONY : EntropyMain.cpp.s

SVM.o: SVM.cpp.o

.PHONY : SVM.o

# target to build an object file
SVM.cpp.o:
	$(MAKE) -f CMakeFiles/SVM.dir/build.make CMakeFiles/SVM.dir/SVM.cpp.o
.PHONY : SVM.cpp.o

SVM.i: SVM.cpp.i

.PHONY : SVM.i

# target to preprocess a source file
SVM.cpp.i:
	$(MAKE) -f CMakeFiles/SVM.dir/build.make CMakeFiles/SVM.dir/SVM.cpp.i
.PHONY : SVM.cpp.i

SVM.s: SVM.cpp.s

.PHONY : SVM.s

# target to generate assembly for a file
SVM.cpp.s:
	$(MAKE) -f CMakeFiles/SVM.dir/build.make CMakeFiles/SVM.dir/SVM.cpp.s
.PHONY : SVM.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... SVM"
	@echo "... Entropy"
	@echo "... edit_cache"
	@echo "... Checker"
	@echo "... Checker.o"
	@echo "... Checker.i"
	@echo "... Checker.s"
	@echo "... Entropy.o"
	@echo "... Entropy.i"
	@echo "... Entropy.s"
	@echo "... EntropyMain.o"
	@echo "... EntropyMain.i"
	@echo "... EntropyMain.s"
	@echo "... SVM.o"
	@echo "... SVM.i"
	@echo "... SVM.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

